export const products = [
  {
    name: "AZEEPURE-200",
    price: "Rs. 95.00",
    composition: "Azithromycin Oral Suspension IP",
    hightlights: [
      "Upper Respiratory Tract Infections",
      "Acute Otitis Media",
      "Skin & Soft Tissue Infections",
      "Typhoid",
      "Bacterial Diarrhea",
    ],
    uses: [
      "Azithromycin is used to treat a wide variety of bacterial infections. It is a macrolide-type antibiotic. It works by stopping the growth of bacteria. This medication will not work for viral infections (such as common cold, flu). Unnecessary use or misuse of any antibiotic can lead to its decreased effectiveness.",
    ],
    howToUse: [
      "- Take this medicine by mouth. Follow the directions on the prescription label.",
      "- For the suspension already mixed by the pharmacist: Shake well before using. This medicine can be taken with food or on an empty stomach. If the medicine upsets your stomach, take it with food.",
      "- For the 1 gram single dose packet: This medicine can be taken with food or on an empty stomach. Empty the contents of a single dose packet into two ounces of water (about one quarter of a full glass).",
      "- Mix and drink all the mixture at once. Add another two ounces of water to the glass, mix well and drink all of it, to make sure you take the full dose.",
    ],
  },
  {
    name: "CVPURE-625",
    price: "Rs. 195.00",
    composition: "Amoxycillin & Potassium Clavulanate Tablet IP",
    hightlights: [
      "Bronchitis",
      "Acute Sinusitis",
      "Post surgical Infections",
      "Bone and joint infections",
      "Skin Infection]",
    ],
    uses: [
      "CVPURE 625 is a penicillin-type of antibiotic that helps your body fight infections caused by bacteria. It is used to treat infections of the lungs (e.g., pneumonia), ear, nasal sinus, urinary tract, skin and soft tissue.",
    ],
    howToUse: [
      "- Broad spectrum combination proving optimum efficacy against both gram positive & gram negative organisms",
      "- Highly active against staphylococcoi, E coli, Haemophilus influenza & klebsiella pneumonia.",
      "- Amoxicillin and Claulvanic Acid extends broad spectrum coverage against beta lactamase stains.",
      "- Achieve superior clinical cure rates compared to clotrimoxazole in UTI.",
    ],
  },
  {
    name: "Purepanta-DSR",
    price: "Rs. 99.00",
    composition:
      "Pantoprazole Gastro-resistant & Domperidone Prolonged-release Capsule IP ",
    hightlights: [
      "Reflux Oesophagitis",
      "Gastritis/Non ulcer Dyspepsia",
      "Gastric/Duodenal ulcer",
      "NSAID/Indused Dyspepsia",
      "Bloating/Fullness/Belching",
    ],
    uses: [
      "It is used in the treatment of gastrointestinal reflux disease, not responding to pantoprazole alone. This condition leads to acid regurgitating from the stomach into the food pipe, causing heartburn, chest discomfort or acidity.",
    ],
    howToUse: [
      "- A potent gastric acid inhibitor that blocks the final stage of acid secretion.",
      "- A potent dopamine receptor blocker improves GI tract motility.",
      "- Facilitates the movement of acid contents further down in the duodenum, jejunum & ileum.",
      "- Promotes contraction of gut wall.",
      "- Quickly relieves heart burn & acid belching.",
    ],
  },
  {
    name: "CIFIPURE-LB",
    price: "Rs. 125.00",
    composition: "Cefixime & Latic Acid Bacillus Dispersible Tablets",
    hightlights: [
      "Bronchitis",
      "Otisis media",
      "Tosillitis",
      "Pharyngitis",
      "Gonorrhea",
      "UTI",
    ],
    uses: [
      "This medication is an oral cephalosporin (third generation) antibiotic, prescribed for gonorrhea, tonsillitis and pharyngitis. It works by fighting against the bacteria in the body.",
    ],
    howToUse: [
      "- Cefixime works to harm the bacteria and fight the infection.",
      "- It works by preventing the formation of the bacterial protective covering which is essential for the survival of bacteria in the human body.",
      "- Lactobacillus is a live micro-organism which restores the balance of good bacteria in the intestine that may get upset with antibiotic use or due to intestinal infections.",
    ],
  },
  {
    name: "PAINPURE-AQ",
    price: "Rs. 21.50",
    composition: "Diclofenac Sodium Injection IP",
    hightlights: [
      "Mild to moderate pain",
      "Swelling",
      "Stiffness",
      "Acute musculoskeletal injuries",
      "Joint pain",
    ],
    uses: [
      "Diclofenac Sodium Injection belongs to a group of medicines called nonsteroidal anti-inflammatory drugs (NSAIDs). It is used for short-term relief of pain, inflammation, and swelling. It works by blocking chemical messengers in the brain that tell us we have pain.",
    ],
    howToUse: [
      "- Diclofenac sodium is a phenylacetic acid derivative that is a white to off-white, virtually odorless, crystalline powder.",
      "- Diclofenac sodium is freely soluble in methanol, soluble in ethanol, and practically insoluble in chloroform and in dilute acid.",
      "- Diclofenac sodium is sparingly soluble in water.",
    ],
  },
  {
    name: "PAINPURE-SP",
    price: "Rs. 99.50",
    composition: "Aceclofenac, Paracetamol & Serrationpeptidase Tablets",
    hightlights: [
      "Headache",
      "Mild migraine",
      "Musculoskeletal pain",
      "Inflammation",
    ],
    uses: [
      "Painpure -SP is a non-steroidal anti-inflammatory drug (NSAID), and Paracetamol is an antipyretic (fever reducer). They work by blocking the release of certain chemical messengers in the brain that cause pain and fever. Serratiopeptidase is an enzyme which works by breaking down abnormal proteins at the site of inflammation and promotes healing.",
    ],
    howToUse: [
      "- You have been prescribed this combination medicine for relieving pain and inflammation.",
      "- Take it with food to avoid getting an upset stomach.",
      "- Avoid consuming alcohol when taking Aceclofenac + Paracetamol + Serratiopeptidase as it may cause excessive drowsiness and increase the risk of liver damage.",
      "- Do not take it with any other medicine containing acetaminophen (drugs for pain/fever or cough-and-cold) without asking your doctor first.",
    ],
  },
  {
    name: "MULTIPRIDE C+",
    price: "Rs. 90.00",
    composition: "Vitamin C, Zinc Sulphate & Vitamin D3 Chewable Tablets",
    hightlights: [
      "Gain Immunity",
      "Healthy and glowing skin",
      "Antioxidant",
      "Lowers your risk of infections and inflammation",
      "Restores the body pool of ascorbic acid",
    ],
    uses: [
      "It is used to help growth and good health. It is used to stop or treat vitamin C deficiency. It is used to lower the urines pH.",
    ],
    howToUse: [
      "-Take with or without food. Take with food if it causes an upset stomach.",
      "- Take with a full glass of water. Mix powder with water and drink.",
      "- Chew or crush well. Mix crushed tablet with food. Do not swallow it whole.",
    ],
  },
  {
    name: "Offpride-oz",
    price: "Rs. 116.00",
    composition:
      "Enteric Coated Pantoprazole Sodium & Sustained Release Domperidone Capsules",
    hightlights: [
      "Diabetic and decubitus Infection",
      "Aspiration Pnuemonia",
      "Surgical wound Infections",
      "Orofacial and dental infections",
      "Skin and soft tissue Infection",
    ],
    uses: [
      "Offpride tablet is used in the treatment of bacterial & parasitic infections. It is used to treat gastrointestinal infections such as acute diarrhea or dysentery, gynecological infections, lung infections and urinary infections.",
    ],
    howToUse: [
      "- Ofloxacin works by preventing the bacterial cells from dividing and repairing, thereby killing the bacteria.",
      "- Ornidazole kills parasites and anaerobic bacteria that cause infections by damaging their DNA. Together, they treat your infection effectively.",
    ],
  },
  {
    name: "Multipride 5G",
    price: "Rs. 189.00",
    composition:
      "Sofgel Capsule of Omega-3 Fatty Acids, Green Tea Extract, Ginko Biboba, Ginseng, Grape Seed Extract, Garlic Oil, Antioxidant, Vitamins, Minerals & Trace Elements",
    hightlights: [
      "High Oxidative Stress",
      "Anorexia",
      "Cachexia Functional Fatigue",
      "Diabetes Obesity",
      "Dyslipidemia Cardiovascular Complications",
    ],
    uses: [
      "Reduces the risk of coronary outcomes and overall mortality",
      "Strengthens the immune system action",
      "Used to alleviate symptoms of age related cognitive impairment",
      "Reduces risk of cardiovascular diseases",
    ],
    howToUse: [
      "- You have been prescribed this combination medicine for relieving pain and inflammation.",
      "- Take it with food to avoid getting an upset stomach.",
      "- Avoid consuming alcohol when taking Aceclofenac + Paracetamol + Serratiopeptidase as it may cause excessive drowsiness and increase the risk of liver damage.",
      "- Do not take it with any other medicine containing acetaminophen (drugs for pain/fever or cough-and-cold) without asking your doctor first.",
    ],
  },
  {
    name: "Multipride Syrup",
    price: "Rs. 145.00",
    composition:
      "Cyanocobalamin Lycopene, Multivitamin, Multiminerals & Antioxidants Syrup in Advanced Formula",
    hightlights: [
      "Convalescence",
      "Vitamin Deficiencies",
      "Macular Degenration",
      "CVS/CNS Disorder",
      "Diabetes",
      "Post Operative",
    ],
    uses: [
      "Prevents Free radicals damage",
      "Promote good muscle tone of digestive system",
      "Enhance Immune system of body",
      "Promotes regenration of degenrating nerve terminals & provides neuronal protections",
    ],
    howToUse: [
      "- You have been prescribed this combination medicine for relieving pain and inflammation.",
      "- Take it with food to avoid getting an upset stomach.",
      "- Avoid consuming alcohol when taking Aceclofenac + Paracetamol + Serratiopeptidase as it may cause excessive drowsiness and increase the risk of liver damage.",
      "- Do not take it with any other medicine containing acetaminophen (drugs for pain/fever or cough-and-cold) without asking your doctor first.",
    ],
  },
  {
    name: "Multipride Drops",
    price: "Rs. 59.00",
    composition: "Multivitamin & Multiminerals with DHA",
    hightlights: [
      "Improve Concentration Level",
      "Promotes Visual Function",
      "Health Brain Development",
      "Imoprove I.Q. Level",
    ],
    uses: [
      "Convenient and Easy-To-Use. It can be consumed directly or in conjunction with food. You can mix it into fruit juice, cereal, milk, or other chilled or room temperature foods to increase your child's acceptance, as DHA has a peculiar marine odor. Idea for 3 months and above.",
      "Supports Cognitive Health and Learning. It also helps improve behavior and mood",
      "Overall Development of Kids: Single source of all the Multivitamins",
      "Delivers 100% of the Daily Value of essential vitamins and minerals, including vitamins A, B and D",
    ],
    howToUse: [
      "- You have been prescribed this combination medicine for relieving pain and inflammation.",
      "- Take it with food to avoid getting an upset stomach.",
      "- Avoid consuming alcohol when taking Aceclofenac + Paracetamol + Serratiopeptidase as it may cause excessive drowsiness and increase the risk of liver damage.",
      "- Do not take it with any other medicine containing acetaminophen (drugs for pain/fever or cough-and-cold) without asking your doctor first.",
    ],
  },
  {
    name: "Cifipure-0",
    price: "Rs. 95.00",
    composition: "Cefixime & Ofloxacin Tablets",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Gestopride 200SR",
    price: "Rs. 95.00",
    composition:
      "Natural Micronized Progesterone Sustained Release Tablets 200 mg",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Enofer-XT",
    price: "Rs. 95.00",
    composition:
      "Ferrous Asparto Glycinate, Methylcobalamin & L-Methylfolate Tablets",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Multipride Injection",
    price: "Rs. 95.00",
    composition:
      "Methylcobalamin, Pyridoxine, Nicotinamide & D-Panthenol Injection",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Koral-Fort",
    price: "Rs. 95.00",
    composition:
      "Coral Calcium, Cyanocobalamin, L-Methylfolate, Vitamin B6, DHA & Vitamin D3 Tablets",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Purepanta-IV",
    price: "Rs. 95.00",
    composition: "Pantoprazole for Injection",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "GERD-RAFT",
    price: "Rs. 95.00",
    composition:
      "Sodium Alginate, Sodium Bicarbonate, Calcium Carbonate Oral Suspension",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "PureCough-LS",
    price: "Rs. 95.00",
    composition: "Ambroxol Hcl, Levosalbutamol & Guaiphenesin Syrup",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "ZYDINE",
    price: "Rs. 95.00",
    composition: "Fungal Diastase, Pepsin & B-Complex Syrup",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Montipure-LC",
    price: "Rs. 95.00",
    composition:
      "Montelukast Sodium & Levocetirizine Hydrochloride Tablets I.P.",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "L-BINO",
    price: "Rs. 95.00",
    composition: "Pre & Probiotic Capsules",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "ARZINO",
    price: "Rs. 95.00",
    composition:
      "L-Arginine Proanthocyanidin, DHA, Vitamin B6, Folic Acid & Lycopene Tablets",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Vonocef 500",
    price: "Rs. 95.00",
    composition: "Cefuroxime Axetil Tablets IP 500mg",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Kocal-D3",
    price: "Rs. 95.00",
    composition: "Cholecalciferol 60,000 IU Softgel Capsules",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
  {
    name: "Painpure-Ace",
    price: "Rs. 95.00",
    composition: "Aceclofenac & Paracetamol Tablets",
    hightlights: [],
    uses: [],
    howToUse: [],
  },
];
